"""State variables used by the advisor agent."""

from enum import StrEnum


class State(StrEnum):
    """State variables used by the advisor agent."""

    USER_QUERY = "user_query"
    """The original query from the user."""

    CLIENT_PROFILE = "client_profile"
    """The client's financial profile, including risk tolerance, investment goals, and time horizon."""

    TODO_LIST = "todo_list"
    """A list of tasks the agent needs to complete to provide a recommendation."""

    CHAT_HISTORY = "chat_history"
    """The history of interactions between the user and the agent, used for context in conversations."""

    REFERENCE_EVALUATIONS = "reference_evaluations"
    """Evaluations of the relevance and quality of retrieved reference materials."""

    ADVISOR_RECOMMENDATION = "advisor_recommendation"
    """The final investment recommendation generated by the advisor agent."""

