"""State variables used by the advisor agent."""

from enum import StrEnum


class State(StrEnum):
    """State variables used by the advisor agent."""

    USER_QUERY = "user_query"
    """The original query from the user."""

    CLIENT_PROFILE = "client_profile"
    """The client's financial profile, including risk tolerance, investment goals, and time horizon."""

    CLIENT_RESPONSE = "client_response"
    """Client feedback on whether the advisor recommendation resolves the conversation."""

    CLIENT_REVIEW_COUNT = "client_review_count"
    """Number of client review iterations completed for this session."""

    TODO_LIST = "todo_list"
    """A list of tasks the agent needs to complete to provide a recommendation."""

    CHAT_HISTORY = "chat_history"
    """The history of interactions between the user and the agent, used for context in conversations."""

    REFERENCE_EVALUATIONS = "reference_evaluations"
    """Evaluations of the relevance and quality of retrieved reference materials."""

    ANALYST_RESEARCH_MODE = "analyst_research_mode"
    """Routing hints for analyst research (list of sources, e.g., ["KB", "WEB"])."""

    ANALYST_FINDINGS = "analyst_findings"
    """Analyst research summary returned to the advisor."""

    ANALYST_CALL_COUNT = "analyst_call_count"
    """Number of analyst agent calls made for the current session."""

    ADVISOR_RECOMMENDATION = "advisor_recommendation"
    """The final investment recommendation generated by the advisor agent."""

